version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    groups:
      eslint:
        patterns: ["eslint", "eslint-*"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: monthly
