name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: echo ::set-output name=nvmrc::$(cat .nvmrc)
        id: nvm
      - uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvm.outputs.nvmrc }}"
          cache: npm
      - run: npm --global install npm@latest
      - run: npm ci
      - run: git config --local user.name '${{ github.actor }}'
      - run: git config --local user.email '${{ github.actor }}@users.noreply.github.com'
      - run: npm run release
      - run: echo "::set-output name=tag::$(git describe --abbrev=0)"
        id: get_tag
      - run: git push --follow-tags
      - run: git tag --force --annotate --message 'Release v1' v1
      - run: git push --tags --force origin v1
      - run: gh release create '${{ steps.get_tag.outputs.tag }}' --notes 'See the [changelog](https://github.com/${{ github.repository }}/blob/${{ steps.get_tag.outputs.tag }}/CHANGELOG.md) for more details.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
