name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]
  # Run the workflow regularly, as auto-merged PRs by bots may not trigger it.
  schedule:
    - cron: "0 0 1,15 * *"
  # Allow manual triggering of the workflow.
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      npm_config_engine_strict: true
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version
          cache: npm
      - run: npm install --global npm@latest
      - run: npm ci
      - run: npm test --ignore-scripts
      - run: npm run test:docker

  lint:
    uses: ybiquitous/.github/.github/workflows/nodejs-lint-reusable.yml@46e5ee1d74cc40a0448a372e22cf3e5852efd59a # v3.0.2
    permissions:
      contents: read
